POST http://{{url}}/api/user/login
Content-Type: application/json

{
  "username": "zhaoo",
  "password": "zhaoo"
}



###
GET http://{{url}}//api/user/logout
Accept: application/json
#X-Token: test-token

###
