POST http://{{url}}/api/user/login
Content-Type: application/json

{
  "username": "zhaoo",
  "password": "zhaoo"
}

###
POST http://{{url}}/api/user/logout
X-Token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoiemhhb28iLCJleHAiOjE1OTA5OTA4NjcsImlhdCI6MTU4OTY5NDg2NywianRpIjoiMSIsImlzcyI6InN5c3RlbSJ9.rDPd6ou7-0GGalFe-9m9p_rWcV4xhGwBJ84RqoTEDUE

###
GET http://{{url}}/api/user/info
X-Token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoiemhhb28iLCJleHAiOjE1OTA5MDc5MzEsImlhdCI6MTU4OTYxMTkzMSwianRpIjoiMSIsImlzcyI6InN5c3RlbSJ9.kvqhMxk1WAwDsNkrzstC2hlB14Wod2XildfP5ZXDJiE


###

POST http://{{url}}/api/user/login
Content-Type: application/json

{
  "mobilePhone": "13588195620"
}



###
GET http://{{url}}//api/user/logout
Accept: application/json
#X-Token: test-token

###
