POST http://{{url}}/test/order
Accept: application/json

{   "id": 64,   "uid": 1,   "totalAmount": 100,   "numPerEquip": 10  }

###
DELETE http://{{url}}/api/order/87
Content-Type: application/json
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoiemhhb28iLCJleHAiOjE1ODQwOTg5ODcsImlhdCI6MTU4MjgwMjk4NywianRpIjoiMSIsImlzcyI6InN5c3RlbSJ9.bYrC5KYElJRs7tWPjQnRGK0OL-6beo2nHobk81bDT0Y



###
POST http://{{url}}/api/pay/refund/90
Content-Type: application/json
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoiemhhb28iLCJleHAiOjE1ODQwOTg5ODcsImlhdCI6MTU4MjgwMjk4NywianRpIjoiMSIsImlzcyI6InN5c3RlbSJ9.bYrC5KYElJRs7tWPjQnRGK0OL-6beo2nHobk81bDT0Y


{
  "adOrderId": 90,
  "refundReason": "测试",
  "refundAmount": 100
}

###
GET http://{{url}}/api/order/list?limit=10
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoiemhhb28iLCJleHAiOjE1ODQwOTg5ODcsImlhdCI6MTU4MjgwMjk4NywianRpIjoiMSIsImlzcyI6InN5c3RlbSJ9.bYrC5KYElJRs7tWPjQnRGK0OL-6beo2nHobk81bDT0Y
Accept: application/json

###
GET http://{{url}}/api/pay/7
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoiemhhb28iLCJleHAiOjE1ODk4MDAzOTUsImlhdCI6MTU4ODUwNDM5NSwianRpIjoiMSIsImlzcyI6InN5c3RlbSJ9.Hhf1-zFOMAWg5vHpxFSj7-NiX1BjtqqMoKkhPrsbNz4
Accept: application/json

###
POST http://{{url}}/api/order/verify
Content-Type:  application/json
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoiemhhb28iLCJleHAiOjE1OTAxMTg1MTYsImlhdCI6MTU4ODgyMjUxNiwianRpIjoiMSIsImlzcyI6InN5c3RlbSJ9.hAWHRZ9y80tMihbNZmf1ntVbJ8qYvLrj5TVjw97TcTc

{
  "feedback": "test",
  "verify": "pass",
  "produceId": 69,
  "id": 40,
  "uid": 1,
  "valueList": []
}

###
POST http://{{url}}/api/order/create
Content-Type:  application/json
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoid2V6aHluIiwiZXhwIjoxNTg0MjU0NDY3LCJpYXQiOjE1ODI5NTg0NjcsImp0aSI6IjEyIiwiaXNzIjoic3lzdGVtIn0.IgX5AYu7JUlbBItMCI8jV0upQWEzi8mbzcNukqRJMvo

{
  "endDate": "2020-02-24T09:49:50.184Z",
  "endTime": "2020-02-24T15:59:59.999Z",
  "latitude": 30.22,
  "longitude": 120.12,
  "num": 100,
  "price": 1,
  "rate": 5,
  "vertical": true,
  "scope": 5,
  "startDate": "2020-02-24T09:49:50.184Z",
  "startTime": "2020-02-23T16:00:00.000Z",
  "valueList": [
    "傻逼儿子"
  ]
}

###


