GET http://{{url}}/api/order/list
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoid2V6aHluIiwiZXhwIjoxNTgyNjcxMDgyLCJpYXQiOjE1ODI2MzUwODIsImp0aSI6IjEyIiwiaXNzIjoic3lzdGVtIn0.IWYBLUhkexnc8E5pBPfzvPq6byotB6BM5rFuo5snVRc
Accept: application/json

###
GET http://{{url}}/api/order/76
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoid2V6aHluIiwiZXhwIjoxNTgyNjcxMDgyLCJpYXQiOjE1ODI2MzUwODIsImp0aSI6IjEyIiwiaXNzIjoic3lzdGVtIn0.IWYBLUhkexnc8E5pBPfzvPq6byotB6BM5rFuo5snVRc
Accept: application/json

###
POST http://{{url}}/api/order/create
Content-Type:  application/json
X-token: eyJhbGciOiJIUzI1NiJ9.eyJhdXRoIjoidXNlciIsInVzZXJuYW1lIjoid2V6aHluIiwiZXhwIjoxNTgyNjcxMDgyLCJpYXQiOjE1ODI2MzUwODIsImp0aSI6IjEyIiwiaXNzIjoic3lzdGVtIn0.IWYBLUhkexnc8E5pBPfzvPq6byotB6BM5rFuo5snVRc

{
  "endDate": "2020-02-24T09:49:50.184Z",
  "endTime": "2020-02-24T15:59:59.999Z",
  "latitude": null,
  "longitude": null,
  "num": 100,
  "price": 1,
  "rate": 5,
  "vertical": true,
  "scope": 5,
  "startDate": "2020-02-24T09:49:50.184Z",
  "startTime": "2020-02-23T16:00:00.000Z",
  "valueList": [
    "傻逼儿子"
  ]
}

###


