apiVersion: v1
kind: Service
metadata:
  name: svc-ad-main
  labels:
    run: ad-main-producer
spec:
  ports:
    - port: 80
      targetPort: 28080
  selector:
    app: ad-main-server
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ad-screen
  labels:
    run: ad-screen
spec:
  type: NodePort
  ports:
    - protocol: tcp
      port: 8188
      targetPort: 8888
  selector:
    app: screen-server
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ad-debug
spec:
  type: NodePort
  ports:
    - port: 5005
      targetPort: 5005
  selector:
    remote: java
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ad-server
spec:
  rules:
    - host: server.zhaoo.icu
      http:
        paths:
          - path: /api
            backend:
              serviceName: svc-ad-main
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-ad-main-server
spec:
  selector:
    matchLabels:
      app: ad-main-server
  replicas: 2
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ad-main-server
        remote: java
    spec:
      containers:
        - name: ad-main-server
          image: registry.cn-hangzhou.aliyuncs.com/wezhyn/ad-main:lastest
          command: ["java"]
          args: ["-jar", "ad-main.jar","--spring.profiles.avtive=zhaoo"]
          imagePullPolicy: "Always"
          tty: true
          ports:
            - containerPort: 12345
            - containerPort: 28080
            - containerPort: 5005
          env:
            - name: TZ
              value: Asia/Shanghai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-screen-server
spec:
  selector:
    matchLabels:
      app: screen-server
  replicas: 2
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: screen-server
        remote: java
    spec:
      containers:
        - name: ad-screen-server
          image: registry.cn-hangzhou.aliyuncs.com/wezhyn/screen-server:lastest
          command: ["java"]
          args: ["-jar", "screen-server.jar","--spring.profiles.avtive=zhaoo"]
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8888
            - containerPort: 5005
          env:
            - name: TZ
              value: Asia/Shanghai