#短期阿里云免费试用数据库配置
custom:
  mysql:
    address: rm-bp1vg4ijefqn9p2r71o.mysql.rds.aliyuncs.com
    password: Mmysql!!
    port: 3306
    username: fkz
    database: fkz
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true

