#custom
custom:
  mysql:
    address: 127.0.0.1
    password: fkz
    port: 3306
    database: fkz
    username: fkz
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true


