server:
  port: 28080
  address: 0.0.0.0
  tomcat:
    max-threads: 8
management:
  security:
    enabled: false
spring:
  profiles:
    active: zhaoo
#     active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${custom.mysql.address}:${custom.mysql.port}/${custom.mysql.database}?${custom.mysql.config}
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 0
      resolve-lazily: false
custom:
  qn:
    access-key: w8q1azRK1pjyjs0Fp-pDEBmhODVOOzL-PbDJTODU
    secret-key: 4lHcLBv6Ywirb0ATkQ62ZnxtC_ONhRyF68Xb-xhG
    bucket-name: qiniu
    host-name: http://qiniu.izhaoo.com
  jwt:
    check-list-exclusion:
      - /api/error
      - /api/test
    check-header: X-Token
    default-hours: 10
    remember-me-day: 1
    login-interception-include:
      user: /api/user/login
      admin: /api/admin/login
    logout-interception:
      - /api/user/logout
      - /api/admin/logout


