server:
  port: 28080
  address: 0.0.0.0
spring:
  profiles:
    active: huawei
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${custom.mysql.address}:${custom.mysql.port}/${custom.mysql.database}?${custom.mysql.config}
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
  #        format_sql: true

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 0
      resolve-lazily: false
custom:
  sms:
    app-id: 1400320689
    app-key: 15474d8d69133abce7c13fbd3736d9f4
    register-template: 540017
    login-template: 540023
    sms-sign: 何事秋风悲画扇
  qn:
    access-key: w8q1azRK1pjyjs0Fp-pDEBmhODVOOzL-PbDJTODU
    secret-key: 4lHcLBv6Ywirb0ATkQ62ZnxtC_ONhRyF68Xb-xhG
    bucket-name: qiniu
    host-name: http://qiniu.izhaoo.com
  jwt:
    check-list-exclusion:
      - /api/error
      - /api/test
    check-header: X-Token
    default-hours: 360
    remember-me-day: 360
    login-interception-include:
      user: /api/user/login
      admin: /api/admin/login
    logout-interception:
      - /api/user/logout
      - /api/admin/logout
netty:
  server:
    address: 0.0.0.0
    port: 8888
    allTimeout: 60


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE