#短期阿里云免费试用数据库配置
custom:
  mysql:
    address: rm-bp1vg4ijefqn9p2r71o.mysql.rds.aliyuncs.com
    password: Mmysql!!
    port: 3306
    username: fkz
    database: fkz
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true

#用于显示绑定的参数具体值
logging:
  level:
    com.ad.admain.controller.quartz.job: error
    org:
      hibernate:
        #        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
