server:
  port: 28080
  address: 0.0.0.0
  tomcat:
    max-threads: 8
rocketmq:
  name-server: 47.111.185.61:9876
  producer:
    group: order-group
#  name-server: 127.0.0.1:9876
management:
  security:
    enabled: false
spring:
  profiles:
    active: tmp
  #     active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${custom.mysql.address}:${custom.mysql.port}/${custom.mysql.database}?${custom.mysql.config}
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 0
      resolve-lazily: false
custom:
  sms:
    app-id: 1400320689
    app-key: 15474d8d69133abce7c13fbd3736d9f4
    register-template: 540017
    login-template: 540023
    sms-sign: 何事秋风悲画扇
  qn:
    access-key: w8q1azRK1pjyjs0Fp-pDEBmhODVOOzL-PbDJTODU
    secret-key: 4lHcLBv6Ywirb0ATkQ62ZnxtC_ONhRyF68Xb-xhG
    bucket-name: qiniu
    host-name: http://qiniu.izhaoo.com
  jwt:
    check-list-exclusion:
      - /api/error
      - /api/test
    check-header: X-Token
    default-hours: 360
    remember-me-day: 360
    login-interception-include:
      user: /api/user/login
      admin: /api/admin/login
    logout-interception:
      - /api/user/logout
      - /api/admin/logout
netty:
  server:
    address: localhost
    port: 8888
    allTimeout: 60


