spring:
  profiles:
    active: tmp
  application:
    name: ad-comsumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${custom.mysql.address}:${custom.mysql.port}/${custom.mysql.database}?${custom.mysql.config}
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8

netty:
  server:
    address: 0.0.0.0
    port: 8888
    allTimeout: 60
dubbo:
  registry:
    username: nacos
    password: nacos
    address: nacos://47.111.185.61
    port: 8848
  consumer:
    group: ${spring.profiles.active}
    version: 1.0.0
    timeout: 5000
rocketmq:
  name-server: 47.111.185.61:9876
  #  name-server: 127.0.0.1:9876
  producer:
    group: order-group
heart:
  producer:
    destination: screen_server_heart

