spring:
  profiles:
    active: huawei
  application:
    name: ad-comsumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${custom.mysql.address}:${custom.mysql.port}/${custom.mysql.database}?${custom.mysql.config}
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8

netty:
  server:
    address: 0.0.0.0
    port: 8888
    allTimeout: 60
heart:
  producer:
    destination: screen_server_heart

logging:
  level:
    com:
      ad:
        screen:
          server:
            handler: debug
