#短期阿里云免费试用数据库配置
custom:
  mysql:
    address: localhost
    password: 123123qwe
    port: 3306
    username: root
    database: fkz
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true
#用于显示绑定的参数具体值
logging:
  level:
    com:
      ad:
        screen:
          server:
            event: warn
            server: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
dubbo:
  registry:
    username: nacos
    password: nacos
    address: nacos://localhost
    port: 8848
  consumer:
    group: ${spring.profiles.active}
    version: 1.0.0
    timeout: 5000
rocketmq:
  name-server: localhost:9876
  producer:
    group: order-group
