server:
  port: 28080
  address: 0.0.0.0
  tomcat:
    max-threads: 8
rocketmq:
  name-server: 47.111.185.61:9876
  producer:
    group: order-group
management:
  security:
    enabled: false
spring:
  profiles:
    active: zhaoo
  #     active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${custom.mysql.address}:${custom.mysql.port}/${custom.mysql.database}?${custom.mysql.config}
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: GMT+8

netty:
  server:
    address: localhost
    port: 8888
    allTimeout: 60


